// GENERATED CODE - DO NOT MODIFY BY HAND
// This is a stub file created for the Drift database code generation.
// In a real Flutter environment, this would be generated by running:
// flutter packages pub run build_runner build

// This file is automatically generated when running the build_runner
// and contains the Drift database implementation code.

// Note: This is a placeholder for the actual generated code.
// The implementation will be generated when the Flutter build process runs.

// Generated implementation would include:
// - _$MunshiDatabase class with table definitions
// - TransactionData data class
// - TransactionsCompanion class for inserts/updates
// - Generated table classes and type converters

export 'munshi_database.dart';