# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do

  desc "Deploy to TestFlight via Github Actions"
  lane :beta do
    # Create and unlock temporary keychain
    create_keychain(
      name: "github_actions_temp_keychain",
      password: ENV['MATCH_PASSWORD'],
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: false
    )

    # Fetch provisioning profiles & signing certificates
    match(
      type: "appstore",
      readonly: true,
      git_basic_authorization: ENV['MATCH_GIT_BASIC_AUTHORIZATION'],
      keychain_name: "github_actions_temp_keychain",
      keychain_password: ENV['MATCH_PASSWORD']
    )

    # Build the Flutter iOS archive via Fastlane's gym
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "sarankar.app.munshi" => "match AppStore sarankar.app.munshi"
        }
      },
      skip_build_archive: false
    )

    # Use the App Store Connect API key (token-based authentication)
    app_store_connect_api_key(
      key_id: '6W3U9Q7XKG',
      issuer_id: 'bca83270-a27f-4398-aceb-2bdb17bff2a2',
      key_filepath: "./AuthKey_6W3U9Q7XKG.p8",
      duration: 1200,
      in_house: false 
    )

    # Upload IPA to TestFlight
    upload_to_testflight(
      skip_waiting_for_build_processing: false,
      distribute_external: false
    )

    # Cleanup keychain
    delete_keychain(name: "github_actions_temp_keychain")

    sh "echo '✅ Successfully uploaded build to TestFlight via GitHub Actions!'"
  end  

end
